- name: Deploy Webpage to nginx/apache
  become: yes
  hosts: servers
  tasks:
    - name: install nginx/apache
      ansible.builtin.apt:
        name: nginx
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: start nginx/apache
      service:
        name: nginx
        enabled: yes
      when: ansible_distribution == 'Ubuntu'

    - name: copy webpage to server distribution
      copy:
        src: index.html
        dest: /var/www/html
      when: ansible_distribution == 'Ubuntu'

    - name: install nginx/apache
      ansible.builtin.yum:
        name: nginx
        state: latest
      when: ansible_distribution in [
        "Amazon",
        "CentOS",
        "RedHat",
        "OracleLinux",
        "AlmaLinux",
        "Rocky"
        ]

    - name: start nginx/apache
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_distribution in [
        "Amazon",
        "CentOS",
        "RedHat",
        "OracleLinux",
        "AlmaLinux",
        "Rocky"
        ]

    - name: copy webpage to server distribution
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: "0644"
      when: ansible_distribution in [
        "Amazon",
        "CentOS",
        "RedHat",
        "OracleLinux",
        "AlmaLinux",
        "Rocky"
        ]
