- name: Install Docker
  hosts: servers
  become: yes
  tasks:
    - name: install docker based on server distribution
      ansible.builtin.apt:
        name: docker.io
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install docker based on Server distribution
      ansible.builtin.yum:
        name: docker
        state: latest
      when: ansible_distribution in [
        "Amazon",
        "CentOS",
        "RedHat",
        "OracleLinux",
        "AlmaLinux",
        "Rocky"
        ]
