- name: Apply Patching activity (Upgrades)
  hosts: servers
  become: yes
  tasks:
    - name: Upgrade servers
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Upgrade Amazon/RHEL servers
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_distribution in [
        "Amazon",
        "CentOS",
        "RedHat",
        "OracleLinux",
        "AlmaLinux",
        "Rocky"
        ]

    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        msg: "Rebooting servers: Patching Activity in progress"
        reboot_timeout: 600
